GraTerenowa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin

from GraTerenowa import settings
from gra import views

app_name = 'gra'
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index, name='index'),
    path('', views.game_index, name='game_index'),
    path('<int:ses_id>/', views.room, name='room'),
    path('zaslepka/', views.zaslepka, name='zaslepka'),
    path('choose_group/', views.choose_group, name='choose_gorup'),
    path('group_screen/', views.group_screen, name='group_screen'),
    path('game_filed/', views.game_filed, name='game_filed'),
    path('host_game_create/', views.host_game_create, name='host_game_create'),
    path('game_creation/', views.game_creation, name='game_creation'),
    path('host_game_filed/', views.host_game_filed, name='host_game_filed'),
    path('group_screen/<int:ekipy_id>/', views.group_screen, name='group_screen'),
    path('update_group_statistic/', views.update_group_statistic, name='update_group_statistic'),
    # path('get_new/', views.newses, name='newses'),
    # path('<int:ses_id>/game/add_score/', views.room, name='name'),
    # path('test_photo', views.test_photo, name='test_photo'),
    path('create_session/creator/<int:ses_id>', views.creator_room, name='creator_room'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gra/models.py
from django.db import models

# Create your models here.
from django.db import models


from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Ekipy(models.Model):
    nazwa_ekipy = models.CharField(max_length=200, default='')
    sesje_ses_number = models.CharField(max_length=200, default='')
    ekipy_id = models.AutoField(primary_key=True)
    ilosc_punktow = models.IntegerField(default=0)
    ilosc_punkow_odwiedzonych = models.IntegerField(default=0)

class Gry(models.Model):
    nr_gry = models.CharField(max_length=200, primary_key=True, default='')
    nazwa_gry = models.CharField(max_length=200, default='')
    czas_trwania = models.CharField(max_length=200, default='')
    lokalizacja = models.CharField(max_length=200, default='')

class Hosty(models.Model):
    h_nick = models.CharField(max_length=200, primary_key=True, default='')
    sesje_ses_number = models.CharField(max_length=200, default='')

class Punktowi(models.Model):
    p_nick = models.CharField(max_length=200, primary_key=True, default='')
    ses_num = models.CharField(max_length=200, default='')
    sesje_ses_number = models.CharField(max_length=200, default='')

class Sesje(models.Model):
    ses_number = models.CharField(max_length=200, default='')
    game_name = models.CharField(max_length=200, default='')
    end_time = models.DateTimeField('end date')
    password = models.CharField(max_length=200, default='')
    gry_nr_gry = models.ForeignKey(Gry, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.ses_number

    def to_delete(self):
        return self.end_time <= timezone.now() - datetime.timedelta(days=7)

class Gracze(models.Model):
    g_nick = models.CharField(max_length = 200, default='')
    score = models.IntegerField(default=0)
    ekipy_ekipy_id = models.ForeignKey(Ekipy, on_delete=models.CASCADE)

    def __str__(self):
        return self.g_nick

class Zadania(models.Model):
    id_zadania = models.CharField(max_length=200, primary_key=True)
    opis_zadania = models.CharField(max_length=200, default='')
    nazwa_zadania = models.CharField(max_length=200, default='')
    lat = models.CharField(max_length=200)
    lon = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    gry_nr_gry = models.ForeignKey(Gry, on_delete=models.CASCADE)

gra/forms.py
from django import forms

class CreateNewSession(forms.Form):
    game_name = forms.CharField(label="Name", max_length=200)

gra/views.py
import string

from django.shortcuts import render, redirect
from django.shortcuts import Http404
from gra.models import Sesje, Gracze, Gry, Zadania, Punktowi, Hosty, Ekipy
import datetime, random, secrets
from django.utils import timezone
from django.http import HttpResponseRedirect
from .forms import CreateNewSession

import matplotlib.pyplot as plt
import io
import base64

# from game.models import Sesje, Gracze
# from game.forms import PostScoreForm
# Create your views here.

def game_index(request):
    return render(request, 'gra/game_index.html')


def check_session_exists(ses_id):
    session_exists = Sesje.objects.filter(ses_number=ses_id).exists()
    return session_exists


def choose_group(request):
    ses_num = request.POST.get('join_code')
    try:
        Sesje.objects.get(ses_number=ses_num)
    except Sesje.DoesNotExist:
        # Jeśli sesja nie istnieje, przekierowanie do 'game_index'
        return redirect('game_index')
    if check_session_exists(ses_num):
        request.session['ses_number'] = str(ses_num)
        ekipy = Ekipy.objects.filter(sesje_ses_number=ses_num) if ses_num else Ekipy.objects.all()

        context = {
            'ekipy': ekipy,
        }
        return render(request, 'gra/choose_group.html', context)


def group_screen(request, ekipy_id=None):
    if request.method == 'POST':
        for key, value in request.POST.items():
            print(f"Klucz: {key}, Wartość: {value}")

        nick = request.POST['nick_hidden']
        ses_number = request.session.get('ses_number')
        request.session['gracz_nick'] = str(nick)
        group_identifier = request.POST['grupa']

        if group_identifier.isdigit():
            # Dodawanie gracza do istniejącej grupy
            ekipa = Ekipy.objects.get(ekipy_id=int(group_identifier))
        else:
            # Tworzenie nowej grupy
            ekipa = Ekipy.objects.create(nazwa_ekipy=group_identifier, sesje_ses_number=ses_number)

        Gracze.objects.create(g_nick=nick, score=0, ekipy_ekipy_id=ekipa)
        czlonkowie = Gracze.objects.filter(ekipy_ekipy_id=ekipa)

        context = {
            'inni_czlonkowie': czlonkowie,
            'tytul': ekipa.nazwa_ekipy,
            'twój_nick': nick
        }
        return render(request, 'gra/group_screen.html', context)  # Przekierowanie do strony powodzenia
    else:
        return render(request, 'gra/group_screen.html')



def game_filed(request):
    ses_number = request.session.get('ses_number')
    g_nick = request.session.get('gracz_nick')
    gracz = Gracze.objects.get(g_nick=g_nick)
    ekipa = Ekipy.objects.get(ekipy_id=gracz.ekipy_ekipy_id_id)
    sesja = Sesje.objects.get(ses_number=ekipa.sesje_ses_number)
    gra = sesja.gry_nr_gry
    tasks = Zadania.objects.filter(gry_nr_gry=gra)
    context = {
        'tasks': tasks
    }
    return render(request, 'gra/game_filed.html', context)


def host_game_create(request):
    if request.method == 'POST':
        for key, value in request.POST.items():
            print(f'Klucz: {key}, Wartość: {value}')

    dostepne_gry = Gry.objects.all()

    request.session['host_nick'] = request.POST.get('host_id')
    request.session['host_pswd'] = request.POST.get('host_password')
    request.session['im_on'] = False

    context = {
        'dostepne_gry': dostepne_gry,
    }
    return render(request, 'gra/host_game_create.html', context)


def game_creation(request):
    if request.method == 'POST':
        for key, value in request.POST.items():
            print(f"{key}: {value}")
    return render(request, 'gra/game_creation.html')


def generate_random_string(length):
    alphabet = string.ascii_letters + string.digits + string.punctuation
    random_string = ''.join(secrets.choice(alphabet) for _ in range(length))
    return random_string


def host_game_filed(request):
    if not request.session.get('im_on'):
        if request.method == 'POST' and not (request.POST.get('index_gry') is not None):
            nazwa_hosta = request.POST.get('nazwa_hosta')
            haslo_hosta = request.POST.get('haslo_hosta')

            # Zapisz dane hosta
            host = Hosty(h_nick=nazwa_hosta, sesje_ses_number="")
            host.save()

            # Utwórz grę
            gra = Gry(nr_gry=generate_random_string(200), nazwa_gry=request.POST.get('nazwa_gry'),
                      czas_trwania=request.POST
                      .get('czas_trwania'), lokalizacja=request.POST.get('localisation'))
            gra.save()

            # Utwórz sesję
            sesja = Sesje(ses_number=generate_random_string(200), game_name="",
                          end_time=timezone.now() + datetime.timedelta(hours=1),
                          password=haslo_hosta, gry_nr_gry=gra)
            sesja.save()

            # Powiąż sesję z hostem
            host.sesje_ses_number = sesja.ses_number
            host.save()

            request.session['ses_number'] = sesja.ses_number

            for key, value in request.POST.items():
                if key.startswith('nazwa_zadania_'):
                    indeks = key.split('_')[-1]
                    nazwa_zadania = value
                    opis_zadania = request.POST.get(f'opis_zadania_{indeks}')
                    haslo_zadania = request.POST.get(f'haslo_zadania_{indeks}')
                    lat_zadania = request.POST.get(f'lat_zadania_{indeks}')
                    lon_zadania = request.POST.get(f'lon_zadania_{indeks}')

                    # Zapisz zadanie
                    zadanie = Zadania(id_zadania=generate_random_string(200), nazwa_zadania=nazwa_zadania,
                                      opis_zadania=opis_zadania, lat=lat_zadania, lon=lon_zadania,
                                      password=haslo_zadania, gry_nr_gry=gra)
                    zadanie.save()

                    # Powiąż zadanie z punktem
                    punkt = Punktowi(p_nick=f"punkt_{indeks}", ses_num=sesja.ses_number,
                                     sesje_ses_number=sesja.ses_number)
                    punkt.save()

            ses_number = request.session['ses_number']
            nazwa_hosta = request.session['host_nick']
            request.session['im_on'] = True

            # Pobranie listy ekip
            sesja = Sesje.objects.get(ses_number=ses_number)
            ekipy = Ekipy.objects.filter(sesje_ses_number=sesja.ses_number)

            points_data = {
                'labels': [],
                'points': []
            }
            visited_points_data = {
                'labels': [],
                'visitedPoints': []
            }

            for ekipa in ekipy:
                points_data['labels'].append(ekipa.nazwa_ekipy)
                points_data['points'].append(ekipa.ilosc_punktow)
                visited_points_data['labels'].append(ekipa.nazwa_ekipy)
                visited_points_data['visitedPoints'].append(ekipa.ilosc_punkow_odwiedzonych)

            context = {
                'ses': str(ses_number),
                'h_nick': str(nazwa_hosta),
                'points_data': points_data,
                'visited_points_data': visited_points_data
            }

            return render(request, 'gra/host_game_filed.html', context)
        elif request.method == 'POST':
            host_nick = request.session.get('host_nick')

            try:
                gra = Gry.objects.get(nr_gry=request.POST.get('index_gry'))
            except Gry.DoesNotExist:
                return redirect('/')

            host = Hosty(h_nick=host_nick, sesje_ses_number="")
            host.save()

            sesja = Sesje(ses_number=generate_random_string(200), game_name="",
                          end_time=timezone.now() + datetime.timedelta(hours=1),
                          password=request.session.get('host_pswd'), gry_nr_gry=gra)
            sesja.save()
            request.session['ses_number'] = sesja.ses_number

            host.sesje_ses_number = sesja.ses_number
            host.save()

            ses_number = request.session['ses_number']
            nazwa_hosta = request.session['host_nick']
            request.session['im_on'] = True

            # Pobranie listy ekip
            sesja = Sesje.objects.get(ses_number=ses_number)
            ekipy = Ekipy.objects.filter(sesje_ses_number=sesja.ses_number)

            points_data = {
                'labels': [],
                'points': []
            }
            visited_points_data = {
                'labels': [],
                'visitedPoints': []
            }

            for ekipa in ekipy:
                points_data['labels'].append(ekipa.nazwa_ekipy)
                points_data['points'].append(ekipa.ilosc_punktow)
                visited_points_data['labels'].append(ekipa.nazwa_ekipy)
                visited_points_data['visitedPoints'].append(ekipa.ilosc_punkow_odwiedzonych)

            context = {
                'ses': str(ses_number),
                'h_nick': str(nazwa_hosta),
                'points_data': points_data,
                'visited_points_data': visited_points_data
            }

            return render(request, 'gra/host_game_filed.html', context)

        # request.session['ses_number'] = sesja.ses_number
        # request.session['host_nick'] = nazwa_hosta

        ses_number = request.session['ses_number']
        nazwa_hosta = request.session['host_nick']
        request.session['im_on'] = True

        # Pobranie listy ekip
        sesja = Sesje.objects.get(ses_number=ses_number)
        ekipy = Ekipy.objects.filter(sesje_ses_number=sesja.ses_number)

        points_data = {
            'labels': [],
            'points': []
        }
        visited_points_data = {
            'labels': [],
            'visitedPoints': []
        }

        for ekipa in ekipy:
            points_data['labels'].append(ekipa.nazwa_ekipy)
            points_data['points'].append(ekipa.ilosc_punktow)
            visited_points_data['labels'].append(ekipa.nazwa_ekipy)

templates/gra/index.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Game</title>
        <!--<link rel="stylesheet" href="game/index_style.css"/>-->

        <!-- Bootstrap4 needed settings -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{% static 'gra/index_style.css' %}">
    </head>
    <body>
{#        <div class="container">#}
{#            <nav class="navbar navbar-toggleable-md navbar-light bg-faded">#}
{#                <h1><a class="navbar-brand" href="">Alkotest</a></h1>#}
{#                <div class="collapse navbar-collapse" id="navbarNav">#}
{#                    <ul class="navbar-nav">#}
{#                        <li class="nav-item mr-0 ml-lg-auto">#}
{#                            <a href=""><img src="{% static 'gra/logo.png' %}"/></a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </nav>#}
{#        </div>#}
        <div class="container">
            <div class="jumbotron">
                <h2>Sesja</h2>
                <br/>
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon">Nr</div>
                        <input id="sesid" type="plain-text" size=20 class="form-control" placeholder="Nr sesji...">
                        <button type="submit" class="btn btn-primary" id="goto">Wejdz</button>
                    </div>
                    <!--<button type="submit" class="btn btn-primary" id="goto">Wejdz</button>-->
            </div>
        </div>

        <div class="container">
            <div class="jumbotron">
                <h3>Dolacz jako host</h3>
                <br/>
                <form class="form-inline" method="POST" action="http://127.0.0.1:8000/hostSes">
                    <input id="sesid" type="text" size=20 class="form-control" placeholder="Nr sesji...">
                    <br/>
                    <input id="sesid" type="password" size=20 class="form-control" placeholder="Haslo...">
                    <button type="submit" class="btn btn-primary" id="behost">Wejdz</button>
                </form>
            </div>
        </div>

        <div class="container">
            <div class="jumbotron">
                <h3>Utwoz nowa</h3>
                <br/>
                <form action="/create_session/">
                    <button type="submit" class="btn btn-primary">Stworz</button>
                </form>
            </div>
        </div>
    </body>

    <script>
      function goToSes() {
        var x = document.getElementById("sesid").value;
        var url = "127.0.0.1:8000/gra/" + x;
        location.replace(x);
      }
      var b = document.getElementById("goto");
      b.addEventListener("click", goToSes, false);
    </script>

</html>

templates/gra/name.html
<form action="<int:ses_id>/gra/add_score/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit">
</form>

templates/gra/room.html
{{ sesja.ses_number }}
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Game</title>
        <!--<link rel="stylesheet" href="game/index_style.css"/>-->

        <!-- Bootstrap4 needed settings -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


        <link rel="stylesheet" type="text/css" href="{% static 'gra/index_style.css' %}">
        <script type="text/javascript" src="https://unpkg.com/tesseract.js@v2.0.0-beta.1/dist/tesseract.min.js"></script>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                <h1><a class="navbar-brand" href="">{{ sesja.game_name }}</a></h1>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item mr-0 ml-lg-auto">
                            <a href=""><img src="/images/grupa_badawcza_logo.png"/></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="container">
            <div class="jumbotron">
                <h2>Sesja nr: {{ sesja.ses_number }}</h2>
                <form class="form-inline" method="GET">
                        <div class="input-group-addon">Invite</div>
                    <button id="invite" type="submit" class="btn btn-primary">Send Invite</button>
                </form>
            </div>
        </div>
        <div class="container">
          <div class="jumbotron">
            <ol>
            {% for gracze in sesja.gracze_set.all %}
              <li>{{ gracze.g_nick }}  {{ gracze.score }} %%%</li>
            {% endfor %}
            </ol>
          </div>
        </div>
        <div class="container">
            <div class="jumbotron">
                <h3>Add your score</h3>
                <br/>
                <!--<form class="form-inline" method="GET">-->
                        <!--<div class="input-group-addon">Add</div>-->
                    <button id="manual" class="btn btn-primary">Add Score</button>
                    <button id="autos" type="submit" class="btn btn-primary">Take Photo</button>
                <!--</form>-->
            </div>
        </div>
        <div class="container" id="unhid" unvisible>
          <div class="jumbotron">
            <form class=form-inline" method="POST" action="">
              {% csrf_token %}
              <input type="text" name="g_nickk"size=20 class="form-control" placeholder="Nick"/>
              <input type="number" name="scoree" size=20 class="form-control" placeholder="Score"/>
              <input type="submit" value="Submit">
            </form>
          </div>
        </div>
        <div id="cameraScore" class="container" unvisible>
          <video id="player" autoplay></video>
          <button id="capture">Capture</button>
          <canvas id="snapshot" width="320" height="240"></canvas>
          <textarea id="result" style="width:640px;height:240px;"></textarea>


          <div class="jumbotron">
            <form class="form-inline" method="POST" action="">
              {% csrf_token %}
              <input type="text" name="g_nickk"size=20 class="form-control" placeholder="Nick"/>
              <input id="photoin" type="number" name="scoree" size=20 class="form-control" placeholder="Score"/>
              <input type="submit" value="Submit">
            </form>
          </div>
        </div>
    </body>

    <script>
      document.getElementById("unhid").style.visibility = "hidden";
      function geturl() {
        alert("Invite: ", + window.location.href);
      }

      function addManualScore() {
        document.getElementById("unhid").style.visibility = "visible";
      }

      var b = document.getElementById("invite");
      b.addEventListener('click', geturl, false);
      var c = document.getElementById("manual");
      document.getElementById("unhid").style.visibility = "hidden";
      c.addEventListener('click', addManualScore, false);

      const player = document.getElementById('player')
      const snapshotZone = document.getElementById('snapshot')
      const captureButton = document.getElementById('capture')
      const result = document.getElementById('result')

      const phin = document.getElementById('photoin')

      function addCameraScore() {
        navigator.mediaDevices.getUserMedia({ video: true }).then(stream => {
          player.srcObject = stream
        })

        captureButton.addEventListener('click', function() {
          const context = snapshot.getContext('2d')
          context.drawImage(player, 0, 0, snapshotZone.width, snapshotZone.height)
          // Tesseract.recognize(snapshotZone, 'jpn', { logger: m => console.log(m) }) // 日本語
          Tesseract.recognize(snapshotZone, 'eng', { logger: m => console.log(m) }) // 英語
          .then(({ data: { text } }) => {
            result.value = text
            phin.value = text
          })
        })
      }
      var d = document.getElementById("autos");
      function addPhotoScore() {
        document.getElementById("cameraScore").style.visibility = "visible";
        addCameraScore();
        window.scrollTo(0,window.scrollY+window.innerHeight*.9);
      }
      d.addEventListener('click', addPhotoScore, false);
    </script>

</html>

templates/gra/tesserac_ex.html
<html>
  <head>
    <meta HTTP-EQUIV="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="https://unpkg.com/tesseract.js@v2.0.0-beta.1/dist/tesseract.min.js"></script>
    <style>
      video {
        position: relative;
        right: 0;
        bottom: 0;
        min-width: 100%;
        min-height: 100%;
        z-index: 0;
      }

      #button {
        position: relative;
        line-height: 12px;
        width: 18px;
        font-size: 8pt;
        margin-top: 1px;
        margin-right: 2px;
        z-index: 1;
      }
    </style>
  </head>
  <body>
    <video id="player" autoplay></video>
    <button id="capture">Capture</button>
    <canvas id="snapshot" width="320" height="240"></canvas>
    <textarea id="result" style="width:640px;height:240px;"></textarea>
  </body>
  <script>
    const player = document.getElementById('player')
    const snapshotZone = document.getElementById('snapshot')
    const captureButton = document.getElementById('capture')
    const result = document.getElementById('result')

    navigator.mediaDevices.getUserMedia({ video: true }).then(stream => {
      player.srcObject = stream
    })

    captureButton.addEventListener('click', function() {
      const context = snapshot.getContext('2d')
      context.drawImage(player, 0, 0, snapshotZone.width, snapshotZone.height)
      // Tesseract.recognize(snapshotZone, 'jpn', { logger: m => console.log(m) }) // 日本語
      Tesseract.recognize(snapshotZone, 'eng', { logger: m => console.log(m) }) // 英語
      .then(({ data: { text } }) => {
        result.value = text
      })
    })
  </script>
</html>